TOP_MODULE += fifo_1r1w
SYNTH_SOURCES += ../fifo_1r1w/fifo_1r1w.sv
SYNTH_SOURCES += ../ram_1r1w_sync/ram_1r1w_sync.sv
SYNTH_SOURCES += ../../kpyd/debounced_kpyd/debounced_kpyd.sv
SYNTH_SOURCES += ../../kpyd/edge_state_machine/edge_state_machine.sv
SYNTH_SOURCES += ../../kpyd/debouncer/debouncer.sv
SYNTH_SOURCES += ../../kpyd/sync/sync.sv
SYNTH_SOURCES += ../../load/load.sv
SYNTH_SOURCES += ../../volume/volume.sv
SYNTH_SOURCES += ../../provided_modules/axis_i2s2.v
SYNTH_SOURCES += ../../provided_modules/inv.sv
SYNTH_SOURCES += ../../provided_modules/dff.sv
NONSYNTH_SOURCES += ../../provided_modules/nonsynth_clock_gen.sv
NONSYNTH_SOURCES += ../../provided_modules/nonsynth_reset_gen.sv
-include ../../simulation.mk
-include ../../fpga.mk
