TOP_MODULE += fifo_1r1w
SYNTH_SOURCES += $(TOP_MODULE).sv
SYNTH_SOURCES += ../ram_1r1w_sync/ram_1r1w_sync.sv
NONSYNTH_SOURCES += ../../provided_modules/nonsynth_clock_gen.sv
NONSYNTH_SOURCES += ../../provided_modules/nonsynth_reset_gen.sv
-include ../../simulation.mk
-include ../../fpga.mk
